export default {
  MAIN: "Main",
  LOGIN: "Login",
  SELECT_ROLE: "Select Role",
  SCAN_CODE: "Scan Code",
  SIGN_UP: "Sign Up",
  HOME: "Home",
  PROFILE: "Profile",
  FEED: "Feed",
  DASHBOARD: "Dashboard",
  CLASS_LIST: "Class List",
  SUBJECT_LIST: "Subject List",
  STUDENT_LIST: "Student List",
  ADD_SECTION: "Add Section",
  ADD_STUDENT: "Add Student",
  STUDENT_PROFILE: "Student Profile",
  EARN_POINTS: "Earn Points",
  REWARDS: "Rewards",
  WALLET: "Wallet",
};
