export default {
  MAIN: "Main",
  LOGIN: "Login",
  SELECT_ROLE: "Select Role",
  SCAN_CODE: "Scan Code",
  SIGN_UP: "Sign Up",
  HOME: "Home",
  PROFILE: "Profile",
  FEED: "Feed",
  DASHBOARD: "Dashboard",
  CLASS_LIST: "Class List",
  STUDENT_LIST: "Student List",
  ADD_CLASS: "Add Class",
  ADD_STUDENT: "Add Student",
  EARN: "Earn",
};
